# Generated by Django 2.2.7 on 2019-11-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
