# Generated by Django 2.2.7 on 2019-11-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191124_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10, null=True),
        ),
    ]
