# Generated by Django 2.2.7 on 2019-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191124_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
