# Generated by Django 2.2.7 on 2019-11-26 03:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191124_2244'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='squirrel',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
