# Generated by Django 2.2.7 on 2019-12-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20191126_0357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='squirrel',
            managers=[
            ],
        ),
    ]
