# Generated by Django 2.2.7 on 2019-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='AM/PM', max_length=2)),
                ('date', models.DateTimeField(help_text='Sighting Session Day and Month (23082019')),
                ('age', models.IntegerField(help_text='Sighting Session Day and Month (23082019')),
            ],
        ),
    ]
