# Generated by Django 2.2.7 on 2019-12-06 02:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='squirrel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
