# Generated by Django 2.2.7 on 2019-11-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Longtitude',
            field=models.FloatField(default=None, help_text='Longtitude', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(default=None, help_text='Latitude', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='location',
            field=models.CharField(default=None, help_text='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='', help_text='Other Activities', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(default='', help_text='Primary Fur Color', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('', '')], default='', help_text='TRUE/FALSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(help_text='Age', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateTimeField(help_text='Date'),
        ),
    ]
