# Generated by Django 2.2.7 on 2019-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191123_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Longtitude',
            field=models.FloatField(help_text='Longtitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(help_text='Latitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(help_text='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(help_text='Primary Fur Color', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(max_length=100),
        ),
    ]
