# Generated by Django 2.2.7 on 2019-11-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191123_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(help_text='Specific Location', max_length=100),
        ),
    ]
